"""War Room — replicates the operator portfolio dashboard.

Run:
    python examples/war_room.py > out/war_room.html
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

# Make `src/` importable when running this file directly.
_HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(_HERE.parent / "src"))

from dashboards import Dashboard, render  # noqa: E402


def build():
    return (
        Dashboard("War Room", subtitle="2026-05-04 portfolio status", theme="palantir")
        .section("Portfolio KPIs", layout="grid")
            .kpi("Sends (7d)", 226, delta="+12", tone="good")
            .kpi("Replies (7d)", 1, delta="+1", tone="good")
            .kpi("Errors (7d)", 4, delta="+4", tone="warn")
            .kpi("Active deploys", 12, tone="neutral")
        .section("Fleet")
            .table(
                caption="Project health (traffic-light)",
                headers=["Project", "Status", "Last Deploy", "Notes"],
                rows=[
                    ["operator-core",     "GREEN",  "2h ago",    "watchdog OK"],
                    ["prospector-pro",    "GREEN",  "1d ago",    "campaign factory live"],
                    ["ai-ops-consulting", "RED",    "20d ago",   "preview deploys ERROR"],
                    ["pool-prospector",   "YELLOW", "4d ago",    "imagen quota near"],
                    ["deal-brain",        "GREEN",  "3d ago",    "stripe stub"],
                ],
            )
        .section("Recent events")
            .timeline([
                {"when": "2026-05-04 12:10", "title": "operator-core deploy", "tone": "good"},
                {"when": "2026-05-03 22:40", "title": "ai-ops preview ERROR", "tone": "bad",
                 "detail": "build crashed in next-build, see preview log"},
                {"when": "2026-05-03 18:05", "title": "prospector-pro: 4 sent / 1 suppressed",
                 "tone": "good"},
            ])
        .section("Open items")
            .callout("ai-ops Vercel previews still ERROR — Codex lane", tone="bad")
            .callout("Postcards lane idle pending Imagen quota refresh", tone="warn")
            .callout("All status files updating on schedule", tone="good")
        .footer("generated by templated-dashboards v0.1.0")
        .build()
    )


def main():
    out_dir = _HERE.parent / "out"
    out_dir.mkdir(exist_ok=True)
    dash = build()
    (out_dir / "war_room.html").write_text(render(dash, "html"), encoding="utf-8")
    (out_dir / "war_room.md").write_text(render(dash, "markdown"), encoding="utf-8")
    (out_dir / "war_room.json").write_text(
        json.dumps(dash.model_dump(exclude_none=True), indent=2),
        encoding="utf-8",
    )
    print(f"wrote: {out_dir/'war_room.html'}")
    print(f"wrote: {out_dir/'war_room.md'}")
    print(f"wrote: {out_dir/'war_room.json'}")


if __name__ == "__main__":
    main()
