"""Fluent Dashboard builder.

Ergonomic shorthand around the Pydantic IR. Designed so the caller
doesn't have to think about ordering or schema details:

    from dashboards import Dashboard, render

    d = (
        Dashboard("War Room", subtitle="2026-05-04")
        .section("Outreach")
            .kpi("Sends", 226, delta="+12")
            .kpi("Replies", 1, tone="good")
        .section("Fleet")
            .table(headers=[...], rows=[...])
        .footer("generated by operator-core")
        .build()
    )
    print(render(d, "html"))

The builder mutates the underlying IR in-place, returns ``self`` from
section-shaping methods, and only validates on ``.build()``.
"""

from __future__ import annotations

from typing import Any, Iterable, List, Optional, Sequence, Union

from . import ir as ir_mod


class _SectionInProgress:
    """Internal handle for the most recently opened section."""

    def __init__(self, section: ir_mod.Section, parent: "Dashboard"):
        self._section = section
        self._parent = parent

    def add(self, component) -> "_SectionInProgress":
        self._section.components.append(component)
        return self


class Dashboard:
    """Fluent builder. Wraps an underlying ``ir.Dashboard``."""

    def __init__(
        self,
        title: str,
        *,
        subtitle: Optional[str] = None,
        theme: str = "palantir",
    ):
        self._title = title
        self._subtitle = subtitle
        self._theme = theme
        self._sections: List[ir_mod.Section] = []
        self._footer: Optional[str] = None
        self._current: Optional[_SectionInProgress] = None

    # ------------------------------------------------------------------
    # structure
    # ------------------------------------------------------------------
    def section(
        self,
        title: str,
        *,
        subtitle: Optional[str] = None,
        layout: str = "stack",
    ) -> "Dashboard":
        s = ir_mod.Section(
            title=title, subtitle=subtitle, layout=layout, components=[]
        )
        self._sections.append(s)
        self._current = _SectionInProgress(s, self)
        return self

    def footer(self, text: str) -> "Dashboard":
        self._footer = text
        return self

    # ------------------------------------------------------------------
    # components — return self so calls chain inside the current section
    # ------------------------------------------------------------------
    def kpi(
        self,
        label: str,
        value: Union[str, int, float],
        *,
        delta: Optional[str] = None,
        tone: str = "neutral",
    ) -> "Dashboard":
        self._require_section("kpi")
        self._current.add(
            ir_mod.KPITile(label=label, value=value, delta=delta, tone=tone)
        )
        return self

    def status_card(
        self,
        project: str,
        *,
        status_url: Optional[str] = None,
        inline_status: Optional[dict] = None,
    ) -> "Dashboard":
        self._require_section("status_card")
        self._current.add(
            ir_mod.StatusCard(
                project=project,
                status_url=status_url,
                inline_status=inline_status,
            )
        )
        return self

    def table(
        self,
        *,
        headers: Sequence[str],
        rows: Iterable[Sequence[Any]],
        caption: Optional[str] = None,
        cell_tones: Optional[Sequence[Sequence[Optional[str]]]] = None,
    ) -> "Dashboard":
        """Render a table.

        v0.3.0 ``cell_tones`` adds optional per-cell color hints. Shape is
        a 2D array matching ``rows``; each cell is one of "good", "warn",
        "bad", "neutral", or None for "no tone". Shorter rows padded with
        None. HTML and Excel renderers color cells; Markdown ignores; PDF
        inherits from HTML.
        """
        self._require_section("table")
        tones_list: Optional[List[List[Optional[str]]]] = None
        if cell_tones is not None:
            tones_list = [list(row) for row in cell_tones]
        self._current.add(
            ir_mod.Table(
                headers=list(headers),
                rows=[list(r) for r in rows],
                caption=caption,
                cell_tones=tones_list,
            )
        )
        return self

    def timeline(self, events: Iterable[dict]) -> "Dashboard":
        self._require_section("timeline")
        evs = [
            ir_mod.TimelineEvent(**e) if isinstance(e, dict) else e for e in events
        ]
        self._current.add(ir_mod.Timeline(events=evs))
        return self

    def callout(
        self,
        text: str,
        *,
        tone: str = "neutral",
        icon: Optional[str] = None,
    ) -> "Dashboard":
        self._require_section("callout")
        self._current.add(ir_mod.Callout(text=text, tone=tone, icon=icon))
        return self

    def chart(
        self,
        kind: str,
        series: Iterable[dict],
        *,
        caption: Optional[str] = None,
    ) -> "Dashboard":
        self._require_section("chart")
        s_models = [
            ir_mod.ChartSeries(**s) if isinstance(s, dict) else s for s in series
        ]
        self._current.add(
            ir_mod.Chart(kind=kind, series=s_models, caption=caption)
        )
        return self

    def pipeline(
        self,
        stages: Iterable[dict],
        *,
        caption: Optional[str] = None,
    ) -> "Dashboard":
        self._require_section("pipeline")
        st = [
            ir_mod.PipelineStage(**s) if isinstance(s, dict) else s for s in stages
        ]
        self._current.add(ir_mod.Pipeline(stages=st, caption=caption))
        return self

    def link_grid(
        self,
        items: Iterable[dict],
        *,
        style: str = "card",
        caption: Optional[str] = None,
    ) -> "Dashboard":
        self._require_section("link_grid")
        it = [ir_mod.LinkItem(**i) if isinstance(i, dict) else i for i in items]
        self._current.add(
            ir_mod.LinkGrid(items=it, style=style, caption=caption)
        )
        return self

    def code_block(
        self,
        text: str,
        *,
        language: Optional[str] = None,
        caption: Optional[str] = None,
    ) -> "Dashboard":
        self._require_section("code_block")
        self._current.add(
            ir_mod.CodeBlock(text=text, language=language, caption=caption)
        )
        return self

    # ------------------------------------------------------------------
    # v0.3.0 components
    # ------------------------------------------------------------------
    def cover_page(
        self,
        title: str,
        *,
        subtitle: Optional[str] = None,
        prepared_for: Optional[str] = None,
        prepared_by: Optional[str] = None,
        version: Optional[str] = None,
        logo_initials: Optional[str] = None,
    ) -> "Dashboard":
        """Add a CoverPage component. Typically placed in its own section
        as the first element of a deliverable."""
        self._require_section("cover_page")
        self._current.add(
            ir_mod.CoverPage(
                title=title,
                subtitle=subtitle,
                prepared_for=prepared_for,
                prepared_by=prepared_by,
                version=version,
                logo_initials=logo_initials,
            )
        )
        return self

    def roi_summary(
        self,
        *,
        investment_usd: float,
        monthly_recovery_usd: float,
        annual_recovery_usd: float,
        multiplier: str,
        payback_months: float,
    ) -> "Dashboard":
        """Add an ROISummary banner."""
        self._require_section("roi_summary")
        self._current.add(
            ir_mod.ROISummary(
                investment_usd=investment_usd,
                monthly_recovery_usd=monthly_recovery_usd,
                annual_recovery_usd=annual_recovery_usd,
                multiplier=multiplier,
                payback_months=payback_months,
            )
        )
        return self

    # ------------------------------------------------------------------
    # finalisation
    # ------------------------------------------------------------------
    def build(self) -> ir_mod.Dashboard:
        return ir_mod.Dashboard(
            title=self._title,
            subtitle=self._subtitle,
            theme=self._theme,
            sections=self._sections,
            footer=self._footer,
        )

    def to_dict(self) -> dict:
        return self.build().model_dump(exclude_none=True)

    # ------------------------------------------------------------------
    def _require_section(self, kind: str) -> None:
        if self._current is None:
            raise RuntimeError(
                f"cannot add {kind} before calling .section(...)"
            )


__all__ = ["Dashboard"]
